-- Auto-generated from schema-map-postgres.psd1 (map@62c9c93)
-- engine: postgres
-- table:  login_attempts
CREATE TABLE IF NOT EXISTS login_attempts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ip_hash BYTEA NOT NULL,
  attempted_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  success BOOLEAN NOT NULL DEFAULT FALSE,
  user_id BIGINT NULL,
  username_hash BYTEA NULL,
  auth_event_id BIGINT NULL,
  CONSTRAINT chk_login_success CHECK (success IN (FALSE, TRUE))
);
